[uvi]
host = ""
port = 0
workers = 0
timeout = 0
debug = false

[db]
port = 0
user = ""
database = ""
echo = false
echo_pool = false
pool_size = 0
max_overflow = 0
host = ""
password = ""

[neo4j]
port = 0
user = ""
db = ""
host = ""
password = ""

[jwt]
algorithm = ""
access_token_expire_minutes = 0
private_key_path = ""
public_key_path = ""
refresh_token_expire_minutes = 0

[ontologies]
OM2 = '__OntologyOM2__'
ChEBI = '__OntologyChEBI__'