services:
  backend:
    build:
      context: ./backend
    environment:
      - DATABASE_URL=postgresql://${PG_USER}:${PG_PASSWORD}@db:5432/${PG_DB}

    depends_on:
      - db
      - neo4j
    expose:
      - 8000

  frontend:
    build:
      context: ./frontend

    depends_on:
      - backend
    ports:
      # - "80:80"
      - "443:443"

    volumes:
      - /app/node_modules
      - ./nginx/frontend.nginx:/etc/nginx/conf.d/default.conf

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}

    expose:
      - 5432

    volumes:
      - pg_data:/var/lib/postgresql/data

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${PG_USER} -d ${PG_DB}" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  backend-nginx:
    image: nginx:latest
    volumes:
      - ./nginx/backend.nginx:/etc/nginx/conf.d/default.conf

    expose:
      - 443
    depends_on:
      - backend

  neo4j:
    image: neo4j:5.20.0
    environment:
      NEO4J_AUTH: ${NEO4J_USER}/${NEO4J_PASSWORD}
      NEO4J_PLUGINS: '["n10s"]'
      NEO4J_server_memory_pagecache_size: 1G
      NEO4J_server_memory_heap_initial__size: 512M
      NEO4J_server_memory_heap_max__size: 1G
      NEO4J_ACCEPT_LICENSE_AGREEMENT: 'yes'
    expose:
      - "7687"
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/import
      - neo4j_plugins:/plugins
    healthcheck:
      test: [ "CMD-SHELL", "curl -fs http://localhost:7474 || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  pg_data:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins: