services:
  backend:
    build:
      context: ./backend
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}

    depends_on:
      - db
    expose:
      - 8000

  frontend:
    build:
      context: ./frontend

    depends_on:
      - backend
    ports:
      - "80:80"
      - "443:443"

    volumes:
      - /app/node_modules
      - ./nginx/frontend.conf:/etc/nginx/conf.d/default.conf

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    expose:
      - 5432

    volumes:
      - pgdata:/var/lib/postgresql/data

  backend-nginx:
    image: nginx:latest
    volumes:
      - ./nginx/backend.conf:/etc/nginx/conf.d/default.conf 

    expose:
      - 443
    depends_on:
      - backend

volumes:
  pgdata:
