"""User reworked, Profile added

Revision ID: 011b4a2a7d81
Revises: b9cb9acd9127
Create Date: 2025-03-05 15:27:54.168775

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '011b4a2a7d81'
down_revision: Union[str, None] = 'b9cb9acd9127'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('surname', sa.String(), nullable=False),
                    sa.Column('registered_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"),
                              nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id']),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_unique_constraint('uq_users_email', 'users', ['email'])
    op.drop_column('users', 'registered_at')
    op.drop_column('users', 'name')
    op.drop_column('users', 'surname')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('surname', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('registered_at', postgresql.TIMESTAMP(),
                                     server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False,
                                     nullable=False))
    op.drop_constraint('uq_users_email', 'users', type_='unique')
    op.drop_table('profiles')
    # ### end Alembic commands ###
