"""username added in user

Revision ID: 0002
Revises: 0001
Create Date: 2025-03-06 01:45:50.632833

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op



# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(), nullable=False))
    op.drop_constraint('uq_users_email', 'users', type_='unique')
    op.create_unique_constraint('uq_users_username', 'users', ['username'])
    op.drop_column('users', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint('uq_users_username', 'users', type_='unique')
    op.create_unique_constraint('uq_users_email', 'users', ['email'])
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
