"""Ontology support

Revision ID: 0005
Revises: 0004
Create Date: 2025-03-16 22:16:33.966040

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0005'
down_revision: Union[str, None] = '0004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ontologies',
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('label', sa.String(), nullable=False),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_ontologies'))
                    )
    op.create_table('column_descriptions',
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('ontology_element', sa.String(), nullable=False),
                    sa.Column('ontology_id', sa.Integer(), nullable=False),
                    sa.Column('experiment_id', sa.Integer(), nullable=False),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['experiment_id'], ['laboratory_experiments.id'],
                                            name=op.f('fk_column_descriptions_experiment_id_laboratory_experiments')),
                    sa.ForeignKeyConstraint(['ontology_id'], ['ontologies.id'],
                                            name=op.f('fk_column_descriptions_ontology_id_ontologies')),
                    sa.PrimaryKeyConstraint('ontology_id', 'experiment_id', 'id', name=op.f('pk_column_descriptions'))
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('column_descriptions')
    op.drop_table('ontologies')
    # ### end Alembic commands ###
