"""Constraints

Revision ID: 0006
Revises: 0005
Create Date: 2025-04-01 01:34:33.857838

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op



# revision identifiers, used by Alembic.
revision: str = '0006'
down_revision: Union[str, None] = '0005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_columns_ontology_id_ontologies', 'columns', type_='foreignkey')
    op.create_foreign_key(op.f('fk_columns_ontology_id_ontologies'), 'columns', 'ontologies', ['ontology_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint('fk_computational_experiments_template_id_computational__efd6', 'computational_experiments', type_='foreignkey')
    op.create_foreign_key(op.f('fk_computational_experiments_template_id_computational_experiment_templates'), 'computational_experiments', 'computational_experiment_templates', ['template_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_computational_experiments_template_id_computational_experiment_templates'), 'computational_experiments', type_='foreignkey')
    op.create_foreign_key('fk_computational_experiments_template_id_computational__efd6', 'computational_experiments', 'computational_experiment_templates', ['template_id'], ['id'])
    op.drop_constraint(op.f('fk_columns_ontology_id_ontologies'), 'columns', type_='foreignkey')
    op.create_foreign_key('fk_columns_ontology_id_ontologies', 'columns', 'ontologies', ['ontology_id'], ['id'])
    # ### end Alembic commands ###
