"""Measurements linked to columns

Revision ID: 0009
Revises: 0008
Create Date: 2025-04-03 05:53:16.535870

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op



# revision identifiers, used by Alembic.
revision: str = '0009'
down_revision: Union[str, None] = '0008'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('computational_experiment_templates', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.create_foreign_key(op.f('fk_measurements_column_columns'), 'measurements', 'columns', ['column'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_measurements_column_columns'), 'measurements', type_='foreignkey')
    op.alter_column('computational_experiment_templates', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.text("nextval('computational_experiment_templates_id_seq'::regclass)"),
               existing_nullable=False)
    # ### end Alembic commands ###
