"""Timezone issues

Revision ID: 0010
Revises: 0009
Create Date: 2025-04-05 03:18:00.959322

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0010'
down_revision: Union[str, None] = '0009'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('experiments', 'created_at',
                    existing_type=postgresql.TIMESTAMP(),
                    type_=sa.TIMESTAMP(timezone=True),
                    existing_nullable=False,
                    existing_server_default=sa.text("timezone('utc'::text, now())"))
    op.alter_column('experiments', 'updated_at',
                    existing_type=postgresql.TIMESTAMP(),
                    type_=sa.TIMESTAMP(timezone=True),
                    existing_nullable=False,
                    existing_server_default=sa.text("timezone('utc'::text, now())"))
    op.alter_column('profiles', 'registered_at',
                    existing_type=postgresql.TIMESTAMP(),
                    type_=sa.TIMESTAMP(timezone=True),
                    existing_nullable=False,
                    existing_server_default=sa.text("timezone('utc'::text, now())"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profiles', 'registered_at',
                    existing_type=sa.TIMESTAMP(timezone=True),
                    type_=postgresql.TIMESTAMP(),
                    existing_nullable=False,
                    existing_server_default=sa.text("timezone('utc'::text, now())"))
    op.alter_column('experiments', 'updated_at',
                    existing_type=sa.TIMESTAMP(timezone=True),
                    type_=postgresql.TIMESTAMP(),
                    existing_nullable=False,
                    existing_server_default=sa.text("timezone('utc'::text, now())"))
    op.alter_column('experiments', 'created_at',
                    existing_type=sa.TIMESTAMP(timezone=True),
                    type_=postgresql.TIMESTAMP(),
                    existing_nullable=False,
                    existing_server_default=sa.text("timezone('utc'::text, now())"))
    # ### end Alembic commands ###
