"""Ontologies table removed

Revision ID: 0011
Revises: 0010
Create Date: 2025-04-07 10:25:54.219403

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0011'
down_revision: Union[str, None] = '0010'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_columns_ontology_id_ontologies', 'columns', type_='foreignkey')
    op.drop_table('ontologies')
    op.alter_column('columns', 'ontology_id', new_column_name='ontology', type_=sa.String)
    op.alter_column('columns', 'ontology_element', new_column_name='ontology_ref')
    # ### end Alembic commands ###


def downgrade() -> None:
    raise Exception('Backward incompatible migration')