"""Templates path

Revision ID: 0013
Revises: 0012
Create Date: 2025-04-18 14:43:34.216402

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0013'
down_revision: Union[str, None] = '0012'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('computational_experiment_templates', sa.Column('path', sa.String(), nullable=False, server_default='/'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('computational_experiment_templates', 'path')
    # ### end Alembic commands ###
