"""Templates owner

Revision ID: 0014
Revises: 0013
Create Date: 2025-04-20 22:06:39.016816

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op



# revision identifiers, used by Alembic.
revision: str = '0014'
down_revision: Union[str, None] = '0013'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('computational_experiment_templates', sa.Column('user_id', sa.BigInteger(), nullable=False))
    op.create_foreign_key(op.f('fk_computational_experiment_templates_user_id_users'), 'computational_experiment_templates', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_computational_experiment_templates_user_id_users'), 'computational_experiment_templates', type_='foreignkey')
    op.drop_column('computational_experiment_templates', 'user_id')
    # ### end Alembic commands ###
