"""Profile extended

Revision ID: 0016
Revises: 0015
Create Date: 2025-05-05 14:47:54.728114

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0016'
down_revision: Union[str, None] = '0015'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('position', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('email', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('last_login', sa.TIMESTAMP(timezone=True), server_default=sa.text("TIMEZONE('utc', now())"), nullable=True))
    op.alter_column('profiles', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('profiles', 'surname',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('profiles', 'registered_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text("timezone('utc'::text, now())"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profiles', 'registered_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text("timezone('utc'::text, now())"))
    op.alter_column('profiles', 'surname',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('profiles', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('profiles', 'last_login')
    op.drop_column('profiles', 'email')
    op.drop_column('profiles', 'position')
    # ### end Alembic commands ###
